export const events = [
    // DAY 1: 17.10.2025
    { name: "TERRORIST TAKEDOWN", club: "MNTC", time: "9:00 AM", venue: "MAB LG 33; LH 32,34", day: 1, category: "competition" },
    { name: "PROTOQUEST", club: "ISTE", time: "9:00 AM", venue: "MAB LH14", day: 1, category: "tech" },
    { name: "HACK-N'-RUSH WITH IOT", club: "AAROHAN", time: "9:00 AM", venue: "TBD", day: 1, category: "tech" },
    { name: "IDEATION HYPERLOOP", club: "AAROHAN", time: "9:00 AM", venue: "TBD", day: 1, category: "competition" },
    { name: "CLASH OF CODERS", club: "RECURSION", time: "9:30 AM", venue: "NAB 401", day: 1, category: "tech" },
    { name: "CRYPTO WORKSHOP", club: "AAROHAN", time: "10:00 AM", venue: "TBD", day: 1, category: "workshop" },
    { name: "BIDWEISER", club: "AAROHAN", time: "10:00 AM", venue: "TBD", day: 1, category: "competition" },
    { name: "GAME", club: "CCA-WDCT", time: "10:00 AM", venue: "NAB 403", day: 1, category: "fun" },
    { name: "HACKOVERFLOW", club: "AAROHAN", time: "12:00 PM", venue: "TBD", day: 1, category: "tech" },
    { name: "SELDOM", club: "CCA-E-CELL", time: "1:00 PM", venue: "ARENA", day: 1, category: "competition" },
    { name: "DEATH NOTE", club: "SAE", time: "2:00 PM", venue: "NAB 402", day: 1, category: "fun" },
    { name: "TECH CHARADES", club: "AAROHAN", time: "2:00 PM", venue: "TBD", day: 1, category: "fun" },
    { name: "MINDSWEEPERS", club: "RECURSION", time: "2:00 PM", venue: "NAB 401", day: 1, category: "tech" },
    { name: "ROBOLIGA", club: "SAE", time: "2:00 PM", venue: "ARENA", day: 1, category: "competition" },
    { name: "AQUARACE", club: "SAE", time: "2:00 PM", venue: "ARENA", day: 1, category: "competition" },
    { name: "ROBOSUMO", club: "SAE", time: "2:00 PM", venue: "ARENA", day: 1, category: "competition" },
    { name: "INVICTUS", club: "CCA", time: "3:00 PM", venue: "NAB 10,11", day: 1, category: "competition" },
    { name: "RIPPLE EFFECT", club: "CCA", time: "4:00 PM", venue: "ARENA", day: 1, category: "fun" },
    { name: "TECH MELA", club: "AAROHAN", time: "5:00 PM", venue: "ARENA", day: 1, category: "fun" },
    { name: "OPENING CEREMONY", club: "AAROHAN", time: "6:00 PM", venue: "MAIN STAGE", day: 1, category: "performance" },
    { name: "BMEP PERFORMANCE", club: "BMEP", time: "7:00 PM", venue: "MAIN STAGE", day: 1, category: "performance" },
    { name: "MUSIC CLUB", club: "Music Club", time: "7:40 PM", venue: "MAIN STAGE", day: 1, category: "performance" },
    { name: "SPICMACAY", club: "SPIC MACAY", time: "8:20 PM", venue: "MAIN STAGE", day: 1, category: "performance" },
    { name: "CROSSVERSE", club: "SAE", time: "Throughout the Day", venue: "ONLINE", day: 1, category: "tech" },
    { name: "MNTC CORNER", club: "MNTC", time: "Throughout the Fest", venue: "TBD", day: 1, category: "corner" },
    { name: "TASVEER (STROKES)", club: "STROKES", time: "Throughout the Fest", venue: "TBD", day: 1, category: "corner" },
    { name: "ARMAGEDDON", club: "AAROHAN", time: "Throughout the Fest", venue: "TBD", day: 1, category: "corner" },
    { name: "GLUG CORNER", club: "GLUG", time: "Throughout the Fest", venue: "TBD", day: 1, category: "corner" },
    { name: "REC ARCADE", club: "RECURSION", time: "Throughout the Fest", venue: "TBD", day: 1, category: "corner" },
    { name: "SAE CORNER", club: "SAE", time: "Throughout the Fest", venue: "TBD", day: 1, category: "corner" },
    { name: "WDCT CORNER", club: "WDCT", time: "Throughout the Fest", venue: "TBD", day: 1, category: "corner" },

    // DAY 2: 18.10.2025
    { name: "CALL OUT SHERLOCK", club: "AAROHAN", time: "9:00 AM", venue: "TBD", day: 2, category: "fun" },
    { name: "HACK-N'-RUSH WITH IOT", club: "AAROHAN", time: "9:00 AM", venue: "TBD", day: 2, category: "tech" },
    { name: "YALI", club: "IEEE", time: "9:00 AM", venue: "NAB 205", day: 2, category: "tech" },
    { name: "ANNUAL CASE STUDY", club: "AAROHAN", time: "9:00 AM", venue: "TBD", day: 2, category: "competition" },
    { name: "NEXUS VERSE", club: "AAROHAN", time: "9:00 AM", venue: "TBD", day: 2, category: "tech" },
    { name: "VALO", club: "AAROHAN", time: "10:00 AM", venue: "TBD", day: 2, category: "fun" },
    { name: "IDEATION HYPERLOOP", club: "AAROHAN", time: "10:00 AM", venue: "TBD", day: 2, category: "competition" },
    { name: "CONJECTURE", club: "CCA", time: "11:00 AM", venue: "NAB 103", day: 2, category: "tech" },
    { name: "SELDOM", club: "CCA-E-CELL", time: "1:00 PM", venue: "ARENA", day: 2, category: "competition" },
    { name: "FIFA ULTIMATE SHOWDOWN", club: "AAROHAN", time: "1:30 PM", venue: "TBD", day: 2, category: "fun" },
    { name: "BE A BILLIONAIRE", club: "CCA", time: "2:00 PM", venue: "NAB 010", day: 2, category: "competition" },
    { name: "MATRIX", club: "MNTC", time: "2:00 PM", venue: "NAB 205", day: 2, category: "tech" },
    { name: "THE NETWORKING PITCH", club: "SAI CELL", time: "2:00 PM", venue: "MAB(TR15,16; LH14)", day: 2, category: "competition" },
    { name: "TEMP TRICK", club: "CCA", time: "2:00 PM", venue: "NAB 303", day: 2, category: "fun" },
    { name: "CONTRAPTIONS", club: "CCA", time: "2:00 PM", venue: "NAB 11", day: 2, category: "tech" },
    { name: "CODECRACKER", club: "AAROHAN", time: "2:00 PM", venue: "TBD", day: 2, category: "tech" },
    { name: "CAR AUCTION", club: "SAE", time: "2:00 PM", venue: "NAB 106", day: 2, category: "fun" },
    { name: "ROBOSUMO", club: "SAE", time: "2:00 PM", venue: "ARENA", day: 2, category: "competition" },
    { name: "SPEED CUBING", club: "AAROHAN", time: "2:00 PM", venue: "ARENA", day: 2, category: "fun" },
    { name: "AQUARACE", club: "SAE", time: "2:00 PM", venue: "ARENA", day: 2, category: "competition" },
    { name: "RECHASE", club: "RECURSION", time: "2:00 PM", venue: "ARENA", day: 2, category: "tech" },
    { name: "ROBOLIGA", club: "SAE", time: "2:00 PM", venue: "ARENA", day: 2, category: "competition" },
    { name: "SQUID GAME", club: "CCA", time: "3:00 PM", venue: "ARENA", day: 2, category: "fun" },
    { name: "ROBO EXPO", club: "AAROHAN", time: "4:00 PM", venue: "TBD", day: 2, category: "tech" },
    { name: "RIPPLE EFFECT", club: "CCA", time: "4:00 PM", venue: "ARENA", day: 2, category: "fun" },
    { name: "TECH MELA", club: "AAROHAN", time: "5:00 PM", venue: "ARENA", day: 2, category: "fun" },
    { name: "GRIDLOCK GAMBIT", club: "AAROHAN", time: "5:00 PM", venue: "TBD", day: 2, category: "fun" },
    { name: "FANTASY FOOTBALL (Prelims)", club: "GLUG", time: "5:00 PM", venue: "NAB 301", day: 2, category: "fun" },
    { name: "DANCE CLUB", club: "Dance Club", time: "6:00 PM", venue: "MAIN STAGE", day: 2, category: "performance" },
    { name: "IGNITIA", club: "AAROHAN", time: "6:30 PM", venue: "MAIN STAGE", day: 2, category: "performance" },
    { name: "INSPIRATIE", club: "AAROHAN", time: "7:50 PM", venue: "MAIN STAGE", day: 2, category: "performance" },
    { name: "BAND (WAVES IN TOWN)", club: "Music Club", time: "8:30 PM", venue: "MAIN STAGE", day: 2, category: "performance" },
    { name: "FOOBAR-CTF", club: "AAROHAN", time: "Throughout the Day", venue: "ONLINE", day: 2, category: "tech" },
    { name: "CROSSVERSE", club: "SAE", time: "Throughout the Day", venue: "ONLINE", day: 2, category: "tech" },
    { name: "MNTC CORNER", club: "MNTC", time: "Throughout the Fest", venue: "TBD", day: 2, category: "corner" },
    { name: "TASVEER (STROKES)", club: "STROKES", time: "Throughout the Fest", venue: "TBD", day: 2, category: "corner" },
    { name: "ARMAGEDDON", club: "AAROHAN", time: "Throughout the Fest", venue: "TBD", day: 2, category: "corner" },
    { name: "GLUG CORNER", club: "GLUG", time: "Throughout the Fest", venue: "TBD", day: 2, category: "corner" },
    { name: "REC ARCADE", club: "RECURSION", time: "Throughout the Fest", venue: "TBD", day: 2, category: "corner" },
    { name: "SAE CORNER", club: "SAE", time: "Throughout the Fest", venue: "TBD", day: 2, category: "corner" },
    { name: "WDCT CORNER", club: "WDCT", time: "Throughout the Fest", venue: "TBD", day: 2, category: "corner" },

    // DAY 3: 19.10.2025
    { name: "BUDGET BATTLE", club: "AAROHAN", time: "9:00 AM", venue: "TBD", day: 3, category: "competition" },
    { name: "SPACE TECH QUIZ", club: "QUIZINC", time: "9:00 AM", venue: "NAB 303", day: 3, category: "tech" },
    { name: "BUILDING & DEVELOPING AI GAMES", club: "CCA", time: "9:00 AM", venue: "NAB 403", day: 3, category: "workshop" },
    { name: "IDEATION HYPERLOOP", club: "AAROHAN", time: "10:00 AM", venue: "TBD", day: 3, category: "competition" },
    { name: "BIDWIT", club: "SAE", time: "10:00 AM", venue: "NAB 11", day: 3, category: "competition" },
    { name: "BGMI", club: "AAROHAN", time: "10:00 AM", venue: "TBD", day: 3, category: "fun" },
    { name: "JOURNO DETECTIVE", club: "AAROHAN", time: "10:00 AM", venue: "TBD", day: 3, category: "fun" },
    { name: "SELDOM", club: "CCA-E-CELL", time: "1:00 PM", venue: "ARENA", day: 3, category: "competition" },
    { name: "BPLAN", club: "AAROHAN", time: "2:00 PM", venue: "TBD", day: 3, category: "competition" },
    { name: "FANTASY FOOTBALL", club: "GLUG", time: "2:00 PM", venue: "NAB 301", day: 3, category: "fun" },
    { name: "CYBER SECURITY & ETICIAL HACKING WORKSHOP", club: "CCA", time: "2:00 PM", venue: "NAB 403", day: 3, category: "workshop" },
    { name: "CLASH OF TITANS", club: "AAROHAN", time: "2:00 PM", venue: "ARENA", day: 3, category: "competition" },
    { name: "ROBOLIGA", club: "SAE", time: "2:00 PM", venue: "ARENA", day: 3, category: "competition" },
    { name: "ROBOSUMO", club: "SAE", time: "2:00 PM", venue: "ARENA", day: 3, category: "competition" },
    { name: "AQUARACE", club: "SAE", time: "2:00 PM", venue: "ARENA", day: 3, category: "competition" },
    { name: "ESCAPE ROOM", club: "CCA", time: "5:00 PM", venue: "ARENA", day: 3, category: "fun" },
    { name: "GRIDLOCK GAMBIT", club: "AAROHAN", time: "6:00 PM", venue: "TBD", day: 3, category: "fun" },
    { name: "PARADIGM CLASH", club: "AAROHAN", time: "6:00 PM", venue: "TBD", day: 3, category: "competition" },
    { name: "ENTERACT", club: "AAROHAN", time: "6:00 PM", venue: "MAIN STAGE", day: 3, category: "performance" },
    { name: "IGNITIA (GAURAV GHAI)", club: "AAROHAN", time: "6:40 PM", venue: "MAIN STAGE", day: 3, category: "performance" },
    { name: "IGNITIA (TANVI BHATT)", club: "AAROHAN", time: "7:20 PM", venue: "MAIN STAGE", day: 3, category: "performance" },
    { name: "SOLO SINGER (EMON CHATTERJEE)", club: "Music Club", time: "8:00 PM", venue: "MAIN STAGE", day: 3, category: "performance" },
    { name: "CROSSVERSE", club: "SAE", time: "Throughout the Day", venue: "ONLINE", day: 3, category: "tech" },
    { name: "FOOBAR-CTF", club: "AAROHAN", time: "Throughout the Day", venue: "ONLINE", day: 3, category: "tech" },
    { name: "MNTC CORNER", club: "MNTC", time: "Throughout the Fest", venue: "TBD", day: 3, category: "corner" },
    { name: "TASVEER (STROKES)", club: "STROKES", time: "Throughout the Fest", venue: "TBD", day: 3, category: "corner" },
    { name: "ARMAGEDDON", club: "AAROHAN", time: "Throughout the Fest", venue: "TBD", day: 3, category: "corner" },
    { name: "GLUG CORNER", club: "GLUG", time: "Throughout the Fest", venue: "TBD", day: 3, category: "corner" },
    { name: "REC ARCADE", club: "RECURSION", time: "Throughout the Fest", venue: "TBD", day: 3, category: "corner" },
    { name: "SAE CORNER", club: "SAE", time: "Throughout the Fest", venue: "TBD", day: 3, category: "corner" },
    { name: "WDCT CORNER", club: "WDCT", time: "Throughout the Fest", venue: "TBD", day: 3, category: "corner" }
];